color0 #13140f
color1 #ffb4ab
color2 #bad064
color3 #c5caa8
color4 #a1d0c4
color5 #bad064
color6 #c5caa8
color7 #e4e2da
color8 #919283
color9 #ffb4ab
color10 #bad064
color11 #c5caa8
color12 #a1d0c4
color13 #bad064
color14 #c5caa8
color15 #e4e2da

cursor                #e4e2da
cursor_text_color     #13140f
background            #13140f
foreground            #e4e2da
selection_foreground  #c7c8b8
selection_background  #46483c
active_border_color   #bad064
inactive_border_color #46483c
url_color             #bad064

active_tab_foreground   #2a3400
active_tab_background   #bad064
inactive_tab_foreground #c7c8b8
inactive_tab_background #46483c
cursor_trail_color      #c7c8b8
