#!/bin/sh

FULL=$(mmsg get focusing-client)
APPID=$(echo "$FULL" | jq .appid | sed -e 's/"//g')
TITLE=$(echo "$FULL" | jq .title | sed -e 's/"//g')

MSG="appid:${APPID},title:${TITLE}"

fyi "Info" "$MSG"

echo "$MSG" | wl-copy
