-- --- fzf-lua ---------------------------------------------
require("fzf-lua").setup({
  "borderless",
})
require("fzf-lua").register_ui_select()

vim.keymap.set("n", "<leader><leader>", function()
  require("fzf-lua").buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>sc", function()
  require("fzf-lua").files({ cwd = "~/.config" })
end, { desc = "Edit configs" })
vim.keymap.set("n", "<leader>sD", function()
  require("fzf-lua").diagnostics_workspace()
end, { desc = "Workspace diagnostics" })
vim.keymap.set("n", "<leader>sd", function()
  require("fzf-lua").diagnostics_document()
end, { desc = "Document diagnostics" })
vim.keymap.set("n", "<leader>sf", function()
  require("fzf-lua").files()
end, { desc = "Find files" })
vim.keymap.set("n", "<leader>sg", function()
  require("fzf-lua").live_grep()
end, { desc = "Live grep" })
vim.keymap.set("n", "<leader>sh", function()
  require("fzf-lua").help_tags()
end, { desc = "Help tags" })
vim.keymap.set("n", "<leader>sk", function()
  require("fzf-lua").keymaps()
end, { desc = "Keymaps" })
vim.keymap.set("n", "<leader>so", function()
  require("fzf-lua").oldfiles()
end, { desc = "Oldfiles/history" })
vim.keymap.set("n", "<leader>sp", function()
  require("fzf-lua").builtin()
end, { desc = "Search pickers" })
vim.keymap.set("n", "<leader>sr", function()
  require("fzf-lua").resume()
end, { desc = "Resume last search" })
vim.keymap.set("n", "<leader>st", function()
  require("fzf-lua").tags_live_grep()
end, { desc = "Tags project (live grep)" })
vim.keymap.set("n", "<leader>sw", function()
  require("fzf-lua").grep_cword()
end, { desc = "Grep word under cursor" })
vim.keymap.set("n", "<leader>sz", function()
  require("fzf-lua").zoxide()
end, { desc = "Zoxide" })
