[swipe.commands.three]
left_up = ""
right_up = ""
up = "qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'Overview'"
left_down = ""
right_down = ""
down = ""
left = ""
right = ""

[swipe.commands.four]
left_up = ""
right_up = ""
up = "qdbus org.kde.kglobalaccel /component/kmix invokeShortcut 'increase_volume'"
left_down = ""
right_down = ""
down = "qdbus org.kde.kglobalaccel /component/kmix invokeShortcut 'decrease_volume'"
left = "xdotool key alt+Left"
right = "xdotool key alt+Right"

[pinch.commands]
in = ""
out = ""

[pinch.settings]
threshold = 0.25
one_shot = false


[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false
