#!/bin/bash

MEDIA_DIR="$HOME/Media"
JELLYFIN_ROOT="/jellyfin"

printf "%s\n" "> Mounting $MEDIA_DIR to $JELLYFIN_ROOT ..." && sudo mount --bind $MEDIA_DIR $JELLYFIN_ROOT

sleep 1

printf "\n%s\n" "---------------------------------------------------------------------------"

printf "\n%s\n" "> Starting jellyfin.service ..." && sudo systemctl start jellyfin

sleep 1

printf "\n%s\n" "---------------------------------------------------------------------------"
printf "%s\n" "Open in http://192.168.1.11:8096/"
printf "%s\n" "Enjoy your Film!"
