#!/bin/sh

config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini"
if [ ! -f "$config" ]; then exit 1; fi

if command -v gsettings >/dev/null; then
  gtk_theme="$(grep 'gtk-theme-name' "$config" | cut -d'=' -f2)"
  icon_theme="$(grep 'gtk-icon-theme-name' "$config" | cut -d'=' -f2)"
  cursor_theme="$(grep 'gtk-cursor-theme-name' "$config" | cut -d'=' -f2)"
  font_name="$(grep 'gtk-font-name' "$config" | cut -d'=' -f2)"

  gnome_schema="org.gnome.desktop.interface"
  gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
  gsettings set "$gnome_schema" icon-theme "$icon_theme"
  # gsettings set "$gnome_schema" color-scheme 'prefer-dark'
  gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
  gsettings set "$gnome_schema" font-name "$font_name"
  # gsettings set "$gnome_schema" text-scaling-factor 1

  gsettings set org.gtk.Settings.FileChooser startup-mode recent # 'recent' or 'cwd'

  ## Enable button and menu icon
  gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ButtonImages': <1>, 'Gtk/MenuImages': <1>}"

  ## Adjust volume in smaller steps
  gsettings set org.gnome.settings-daemon.plugins.media-keys volume-step 2

 # Disable `Super + Num` keyboard shortcut so I can use that to navigate between workspace
  gsettings set org.gnome.shell.keybindings switch-to-application-1 []
  gsettings set org.gnome.shell.keybindings switch-to-application-2 []
  gsettings set org.gnome.shell.keybindings switch-to-application-3 []
  gsettings set org.gnome.shell.keybindings switch-to-application-4 []
  gsettings set org.gnome.shell.keybindings switch-to-application-5 []
  gsettings set org.gnome.shell.keybindings switch-to-application-6 []
  gsettings set org.gnome.shell.keybindings switch-to-application-7 []
  gsettings set org.gnome.shell.keybindings switch-to-application-8 []
  gsettings set org.gnome.shell.keybindings switch-to-application-9 []

  # Vim-Keybindings
  gsettings set org.gnome.shell.app-switcher current-workspace-only false
  # gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Alt>Tab']"
  # gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Alt>Tab']"
  # gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Super>Tab']"
  # gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "['<Shift><Super>Tab']"
  #
  # gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Super>1']"
  # gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Super>2']"
  # gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Super>3']"
  # gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Super>4']"
  #
  # gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Super><Shift>Page_Down', '<Super><Shift>p']"
  # gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Super><Shift>Page_Up', '<Super><Shift>n']"
  # gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Page_Down', '<Super>p']"
  # gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Page_Up', '<Super>n']"
  
  # gsettings set org.gnome.desktop.wm.keybindings maximize "['<Super>Up', '<Super>k']"
  # gsettings set org.gnome.desktop.wm.keybindings unmaximize "['<Super>Down', '<Alt>F5', '<Super>j']"

fi
