matches:
  - trigger: ":ai"
    replace: "{{snippet}}"
    vars:
      - name: files
        type: shell
        params:
          cmd: "find ~/.config/espanso/snippets -maxdepth 1 -type f -name '*.md' ! -name 'README.md'"
      - name: picker
        type: form
        params:
          layout: |
            Select file:
            [[file]]
          fields:
            file:
              type: list
              values: "{{files}}"
      - name: snippet
        type: shell
        params:
          cmd: "cat {{picker.file}}"
