# ----------------------------
# Scractpad
# ----------------------------
# scratchpad_width_ratio=0.8
# scratchpad_height_ratio=0.7
single_scratchpad=0

bind=SUPER,minus,toggle_scratchpad

bind=SUPER,grave,toggle_named_scratchpad,scratchpad,none,kitty --app-id=scratchpad
windowrule=isnamedscratchpad:1,width:1080,height:720,appid:scratchpad

# bind=SUPER,period,toggle_named_scratchpad,notes,none,kitty --app-id=notes -d ~/Grimoire/Notes
# windowrule=isnamedscratchpad:1,width:440,height:790,offsetx:120,offsety:180,no_force_center:1,,appid:notes

# bind=SUPER,backslash,toggle_named_scratchpad,scratch-yazi,yazi,kitty --app-id=scratch-yazi -e yazi
# windowrule=isnamedscratchpad:1,width:1080,height:720,appid:scratch-yazi

# bind=CTRL,backslash,spawn,~/.config/mango/script/macro.sh
# bind=NONE,XF86Fn,spawn,~/.config/mango/script/macro.sh

# bind=SUPER,backslash,toggle_named_scratchpad,macro-edit,none,kitty --app-id=macro-edit -e nvim ~/.config/mango/script/macro.sh
# windowrule=isnamedscratchpad:1,width:1080,height:720,appid:macro-edit
