--password-store=basic
# --enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
# --enable-features=Vulkan
# --enable-features=CompositorThreadedScrollbarScrolling
# --enable-features=ThrottleDisplayNoneAndVisibilityHiddenCrossOriginIframes
--ignore-gpu-blacklist
--enable-gpu-rasterization
--enable-zero-copy
# --enable-parallel-downloading
# --no-first-run
# --renderer-process-limit=4
# --disable-domain-reliability
# --ozone-platform=wayland
# --enable-features=WaylandWindowDecorations,WaylandTextInputV3
