--password-store=basic
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL
--ignore-gpu-blacklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-parallel-downloading
