--password-store=basic
--ignore-gpu-blacklist
--enable-gpu-rasterization
--enable-zero-copy
--ozone-platform=wayland
--enable-features=WaylandWindowDecorations
--enable-features=ThrottleDisplayNoneAndVisibilityHiddenCrossOriginIframes
--renderer-process-limit=6
