#!/bin/sh
# vim: ft=sh ts=4 sw=4:

brightness_step=5
bar_color="#b3cfa7"

_get() { brightnessctl info | grep Current | awk '{print $4}' | tr -d '%' | tr -d  '(' | tr -d ')'; }

notify() {
    brightness=$(_get)
    brightness_icon=""
    dunstify -t 1000 -r 2593 -u normal "$brightness_icon $brightness%" \
        -h int:value:$brightness -h string:hlcolor:$bar_color
}

case "$1" in
    up)
        brightnessctl -q -c backlight set "$brightness_step"%+
        notify
    ;;
    down)
        brightnessctl -q -c backlight set "$brightness_step"%-
        notify
    ;;
esac
