#!/bin/sh

MPD_PORT=$(grep port ~/.config/mpd/mpd.conf | head -n1 | sed -e 's#port##' | sed -e 's# ##g' | sed -e 's#"##g')

prev="mpc -p ${MPD_PORT:-6600} -q prev"
toggle="mpc -p ${MPD_PORT:-6600} -q toggle"
stop="mpc -p ${MPD_PORT:-6600} -q stop"
next="mpc -p ${MPD_PORT:-6600} -q next"
title="$(mpc --format '[%title%|%file%]' current)"
status="$(mpc -p ${MPD_PORT:-6600} status)"

case "$1" in
    toggle|play-pause|pause) sh -c "$toggle" ;;
    stop) sh -c "$stop" ;;
    next) sh -c "$next" ;;
    previous|prev) sh -c "$prev" ;;
    status) echo "$status" ;;
    title) echo "$title" ;;
    "-h" | "--help") help ;;
    *) echo "Invalid" && help ;;
esac
