#!/bin/bash
# shellcheck disable=SC2010

LIST=$(ls "${XDG_CONF_DIR:-$HOME/.config}" | grep 'nvim')
CONFIG=$(echo "$LIST" |  fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)

if [ -z $CONFIG ]; then
    echo "Nothing selected"; exit;
elif [ $CONFIG == "default" ]; then
    CONFIG="nvim"
fi
NVIM_APPNAME=$CONFIG nvim "$@"
