#!/bin/sh
# vim: ft=sh ts=4 sw=4:

bar_color="#b3cfa7"
max_volume=100
volume_step=2

_get(){ pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1; }
_get_mute(){ pactl get-sink-mute @DEFAULT_SINK@ | grep -Po '(?<=Mute: )(yes|no)'; }

notify() {
    volume=$(_get)
    mute=$(_get_mute)

    if [ "$volume" -eq 0 ] || [ "$mute" = "yes" ] ; then
        volume_icon="M"
    elif [ "$volume" -lt 50 ]; then
        volume_icon=""
    else
        volume_icon=""
    fi

    dunstify -i audio-volume-muted-blocking -t 1000 -r 2593 -u normal "$volume_icon $volume%" \
        -h int:value:$volume -h string:hlcolor:$bar_color
}


case "$1" in
    up)
        # Unmutes and increases volume, then displays the notification
        pactl set-sink-mute @DEFAULT_SINK@ 0
        volume=$(_get)
        if [ $(( "$volume" + "$volume_step" )) -gt $max_volume ]; then
            pactl set-sink-volume @DEFAULT_SINK@ $max_volume%
        else
            pactl set-sink-volume @DEFAULT_SINK@ +$volume_step%
        fi
        notify
    ;;
    down)
        # Raises volume and displays the notification
        pactl set-sink-volume @DEFAULT_SINK@ -$volume_step%
        notify
    ;;
    mute)
        # Toggles mute and displays the notification
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        notify
    ;;
esac
