"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 500
command_timeout = 1000

[container]
format = '[$symbol \[$name\]]($style) '

[hostname]
ssh_only = false
format = 'on [$hostname](bold red) [$ssh_symbol](bold blue) '
disabled = false
