# Hermes Agent fish completion
# Add to your config:
#   hermes completion fish | source

# Helper: list available profiles
function __hermes_profiles
    echo default
    if test -d $HOME/.hermes/profiles
        ls $HOME/.hermes/profiles 2>/dev/null
    end
end

# Disable file completion by default
complete -c hermes -f

# Complete profile names after -p / --profile
complete -c hermes -f -s p -l profile -d 'Profile name' -xa '(__hermes_profiles)'

# Top-level subcommands
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a acp -d 'Run Hermes Agent as an ACP (Agent Client Protocol) server'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a auth -d 'Manage pooled provider credentials'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a backup -d 'Back up Hermes home directory to a zip file'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a chat -d 'Interactive chat with the agent'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a checkpoints -d 'Inspect / prune / clear ~/.hermes/checkpoints/'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a claw -d 'OpenClaw migration tools'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a completion -d 'Print shell completion script (bash, zsh, or fish)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a computer-use -d 'Manage the Computer Use (cua-driver) backend (macOS)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a config -d 'View and edit configuration'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a cron -d 'Cron job management'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a curator -d 'Background skill maintenance (curator) — status, run, pause,'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a dashboard -d 'Start the web UI dashboard'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a debug -d 'Debug tools — upload logs and system info for support'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a doctor -d 'Check configuration and dependencies'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a dump -d 'Dump setup summary for support/debugging'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a fallback -d 'Manage fallback providers (tried when the primary model fail'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a gateway -d 'Messaging gateway management'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a hooks -d 'Inspect and manage shell-script hooks'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a import -d 'Restore a Hermes backup from a zip file'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a insights -d 'Show usage insights and analytics'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a kanban -d 'Multi-profile collaboration board (tasks, links, comments)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a login -d 'Authenticate with an inference provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a logout -d 'Clear authentication for an inference provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a logs -d 'View and filter Hermes log files'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a lsp -d 'Language Server Protocol management'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a mcp -d 'Manage MCP servers and run Hermes as an MCP server'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a memory -d 'Configure external memory provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a model -d 'Select default model and provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a pairing -d 'Manage DM pairing codes for user authorization'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a plugins -d 'Manage plugins — install, update, remove, list'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a profile -d 'Manage profiles — multiple isolated Hermes instances'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a sessions -d 'Manage session history (list, rename, export, prune, delete)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a setup -d 'Interactive setup wizard'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a skills -d 'Search, install, configure, and manage skills'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a slack -d 'Slack integration helpers (manifest generation, etc.)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a status -d 'Show status of all components'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a tools -d 'Configure which tools are enabled per platform'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a uninstall -d 'Uninstall Hermes Agent'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a update -d 'Update Hermes Agent to the latest version'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a version -d 'Show version information'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a webhook -d 'Manage dynamic webhook subscriptions'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp auth backup chat checkpoints claw completion computer-use config cron curator dashboard debug doctor dump fallback gateway hooks import insights kanban login logout logs lsp mcp memory model pairing plugins profile sessions setup skills slack status tools uninstall update version webhook whatsapp' -a whatsapp -d 'Set up WhatsApp integration'

# Subcommand completions
# auth
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a add -d 'Add a pooled credential'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a list -d 'List pooled credentials'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a logout -d 'Log out a provider and clear stored auth state'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a remove -d 'Remove a pooled credential by index, id, or label'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a reset -d 'Clear exhaustion status for all credentials for a provider'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a spotify -d 'Authenticate Hermes with Spotify via PKCE'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a status -d 'Show auth status for a provider'
# checkpoints
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a clear -d 'Delete the entire checkpoint base (all /rollback history)'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a clear-legacy -d 'Delete only the legacy-<ts>/ archives from v1 migration'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a list -d 'Alias for status'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a prune -d 'Delete orphan/stale checkpoints and GC the store'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a status -d 'Show total size, project count, and per-project breakdown'
# claw
complete -c hermes -f -n '__fish_seen_subcommand_from claw' -a cleanup -d 'Archive leftover OpenClaw directories after migration'
complete -c hermes -f -n '__fish_seen_subcommand_from claw' -a migrate -d 'Migrate from OpenClaw to Hermes'
# computer-use
complete -c hermes -f -n '__fish_seen_subcommand_from computer-use' -a install -d 'Install or repair the cua-driver binary (macOS)'
complete -c hermes -f -n '__fish_seen_subcommand_from computer-use' -a status -d 'Print whether cua-driver is installed and on PATH'
# config
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a check -d 'Check for missing/outdated config'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a edit -d 'Open config file in editor'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a env-path -d 'Print .env file path'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a migrate -d 'Update config with new options'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a path -d 'Print config file path'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a set -d 'Set a configuration value'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a show -d 'Show current configuration'
# cron
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a create -d 'Create a scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a edit -d 'Edit an existing scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a list -d 'List scheduled jobs'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a pause -d 'Pause a scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a remove -d 'Remove a scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a resume -d 'Resume a paused job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a run -d 'Run a job on the next scheduler tick'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a status -d 'Check if cron scheduler is running'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a tick -d 'Run due jobs once and exit'
# curator
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a archive -d 'Manually archive a skill (move to .archive/, excluded from p'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a backup -d 'Take a manual tar.gz snapshot of ~/.hermes/skills/ (curator '
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a list-archived -d 'List archived skills'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a pause -d 'Pause the curator until resumed'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a pin -d 'Pin a skill so the curator never auto-transitions it'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a prune -d 'Bulk-archive agent-created skills idle for >= N days (defaul'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a restore -d 'Restore an archived skill'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a resume -d 'Resume a paused curator'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a rollback -d 'Restore ~/.hermes/skills/ from a curator snapshot (defaults '
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a run -d 'Trigger a curator review now'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a status -d 'Show curator status and skill stats'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a unpin -d 'Unpin a skill'
# debug
complete -c hermes -f -n '__fish_seen_subcommand_from debug' -a delete -d 'Delete a paste uploaded by hermes debug share'
complete -c hermes -f -n '__fish_seen_subcommand_from debug' -a share -d 'Upload debug report to a paste service and print a shareable'
# fallback
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a add -d 'Pick a provider + model (same picker as `hermes model`) and '
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a clear -d 'Remove all fallback entries'
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a list -d 'Show the current fallback chain (default when no subcommand)'
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a remove -d 'Pick an entry to delete from the chain'
# gateway
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a install -d 'Install gateway as a systemd/launchd background service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a list -d 'List all profiles and their gateway status'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a migrate-legacy -d 'Remove legacy hermes.service units from pre-rename installs'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a restart -d 'Restart gateway service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a run -d 'Run gateway in foreground (recommended for WSL, Docker, Term'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a setup -d 'Configure messaging platforms'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a start -d 'Start the installed systemd/launchd background service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a status -d 'Show gateway status'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a stop -d 'Stop gateway service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a uninstall -d 'Uninstall gateway service'
# hooks
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a doctor -d 'Check each configured hook: exec bit, allowlist, mtime drift'
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a list -d 'List configured hooks with matcher, timeout, and consent sta'
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a revoke -d 'Remove a commands allowlist entries (takes effect on next re'
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a test -d 'Fire every hook matching <event> against a synthetic payload'
# kanban
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a archive -d 'Archive one or more tasks'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a assign -d 'Assign or reassign a task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a assignees -d 'List known profiles + per-profile task counts (union of ~/.h'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a block -d 'Mark one or more tasks blocked'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a boards -d 'Manage kanban boards (one board per project / workstream)'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a claim -d 'Atomically claim a ready task (prints resolved workspace pat'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a comment -d 'Append a comment'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a complete -d 'Mark one or more tasks done'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a context -d 'Print the full context a worker sees for a task (title + bod'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a create -d 'Create a new task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a daemon -d 'DEPRECATED — dispatcher now runs in the gateway. Use `hermes'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a diagnostics -d 'List active diagnostics on the current board'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a dispatch -d 'One dispatcher pass: reclaim stale, promote ready, spawn wor'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a edit -d 'Edit recovery fields on an already-completed task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a gc -d 'Garbage-collect archived-task workspaces, old events, and ol'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a heartbeat -d 'Emit a heartbeat event for a running task (worker liveness s'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a init -d 'Create kanban.db if missing (idempotent)'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a link -d 'Add a parent->child dependency'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a list -d 'List tasks'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a log -d 'Print the worker log for a task (from <kanban-root>/kanban/l'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a notify-list -d 'List notification subscriptions (optionally for a single tas'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a notify-subscribe -d 'Subscribe a gateway source to a tasks terminal events (used '
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a notify-unsubscribe -d 'Remove a gateway subscription from a task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a reassign -d 'Reassign a task to a different profile, optionally reclaimin'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a reclaim -d 'Release an active worker claim on a running task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a runs -d 'Show attempt history for a task (one row per run: profile, o'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a show -d 'Show a task with comments + events'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a specify -d 'Flesh out a triage-column task into a concrete spec (title +'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a stats -d 'Per-status + per-assignee counts + oldest-ready age'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a tail -d 'Follow a tasks event stream'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a unblock -d 'Return one or more blocked tasks to ready'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a unlink -d 'Remove a parent->child dependency'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a watch -d 'Live-stream task_events to the terminal (Ctrl+C to exit)'
# lsp
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a install -d 'Install a server binary'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a install-all -d 'Install every server with a known auto-install recipe'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a list -d 'List supported language servers'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a restart -d 'Tear down running LSP clients (next edit re-spawns)'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a status -d 'Show LSP service status'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a which -d 'Print binary path for a server'
# mcp
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a add -d 'Add an MCP server (discovery-first install)'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a configure -d 'Toggle tool selection'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a list -d 'List configured MCP servers'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a login -d 'Force re-authentication for an OAuth-based MCP server'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a remove -d 'Remove an MCP server'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a serve -d 'Run Hermes as an MCP server (expose conversations to other a'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a test -d 'Test MCP server connection'
# memory
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a off -d 'Disable external provider (built-in only)'
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a reset -d 'Erase all built-in memory (MEMORY.md and USER.md)'
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a setup -d 'Interactive provider selection and configuration'
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a status -d 'Show current memory provider config'
# pairing
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a approve -d 'Approve a pairing code'
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a clear-pending -d 'Clear all pending codes'
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a list -d 'Show pending + approved users'
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a revoke -d 'Revoke user access'
# plugins
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a disable -d 'Disable a plugin without removing it'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a enable -d 'Enable a disabled plugin'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a install -d 'Install a plugin from a Git URL or owner/repo'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a list -d 'List installed plugins'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a remove -d 'Remove an installed plugin'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a update -d 'Pull latest changes for an installed plugin'
# profile
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a alias -d 'Manage wrapper scripts'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a create -d 'Create a new profile'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a delete -d 'Delete a profile'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a export -d 'Export a profile to archive'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a import -d 'Import a profile from archive'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a info -d 'Show a profiles distribution manifest (version, requirements'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a install -d 'Install a profile distribution from a git URL or local direc'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a list -d 'List all profiles'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a rename -d 'Rename a profile'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a show -d 'Show profile details'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a update -d 'Re-pull a distribution and apply updates (user data preserve'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a use -d 'Set sticky default profile'
complete -c hermes -f -n '__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from export; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from rename; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from show; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from use; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
# sessions
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a browse -d 'Interactive session picker — browse, search, and resume sess'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a delete -d 'Delete a specific session'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a export -d 'Export sessions to a JSONL file'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a list -d 'List recent sessions'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a prune -d 'Delete old sessions'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a rename -d 'Set or change a sessions title'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a stats -d 'Show session store statistics'
# skills
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a audit -d 'Re-scan installed hub skills'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a browse -d 'Browse all available skills (paginated)'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a check -d 'Check installed hub skills for updates'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a config -d 'Interactive skill configuration — enable/disable individual '
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a inspect -d 'Preview a skill without installing'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a install -d 'Install a skill'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a list -d 'List installed skills'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a publish -d 'Publish a skill to a registry'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a reset -d 'Reset a bundled skill — clears user-modified tracking so upd'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a search -d 'Search skill registries'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a snapshot -d 'Export/import skill configurations'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a tap -d 'Manage skill sources'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a uninstall -d 'Remove a hub-installed skill'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a update -d 'Update installed hub skills'
# slack
complete -c hermes -f -n '__fish_seen_subcommand_from slack' -a manifest -d 'Print or write a Slack app manifest with every gateway comma'
# tools
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a disable -d 'Disable toolsets or MCP tools'
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a enable -d 'Enable toolsets or MCP tools'
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a list -d 'Show all tools and their enabled/disabled status'
# webhook
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a list -d 'List all dynamic subscriptions'
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a remove -d 'Remove a subscription'
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a subscribe -d 'Create a webhook subscription'
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a test -d 'Send a test POST to a webhook route'

