os:
  editPreset: 'nvim'
git:
  pagers:
    - pager: delta --dark --paging=never
    - pager: delta --dark --paging=never --side-by-side
    - useExternalDiffGitConfig: true
gui:
  nerdFontsVersion: "3"
