# Autostart
exec-once=qs -c noctalia-shell
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Persistent clipboard history
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --watch cliphist store &

# The command is not necessary. It is only to avoid some situations where it cannot start automatically
exec-once=/usr/lib/xdg-desktop-portal-wlr &

exec-once=sleep 5 && kitty
exec-once=sleep 7 && brave

