# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x475258ff
rootcolor = 0x232a2eff
bordercolor = 0x7a8478ff
dropcolor = 0xa7c08080
splitcolor = 0x9da9a0ff
focuscolor = 0xa7c080ff
maximizescreencolor = 0xd3c6aaff
urgentcolor = 0xe67e80ff
scratchpadcolor = 0x9da9a0ff
globalcolor = 0x4e6924ff
overlaycolor = 0x957736ff
