# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x141316ff
bordercolor = 0x938f99ff
focuscolor = 0xcbbeffff
maximizescreencolor = 0xcac3dcff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xeeb8cbff
globalcolor = 0x4a398cff
overlaycolor = 0x484458ff
