# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x13140fff
bordercolor = 0x919283ff
focuscolor = 0xbad064ff
maximizescreencolor = 0xc5caa8ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xa1d0c4ff
globalcolor = 0x3f4c00ff
overlaycolor = 0x444930ff
