# ----------------------------
# Scractpad
# ----------------------------
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.6
single_scratchpad=0

bind=SUPER,minus,toggle_scratchpad

bind=SUPER,grave,toggle_named_scratchpad,scratch,none,kitty --app-id=scratch
windowrule=isnamedscratchpad:1,width:1080,height:720,appid:scratch

bind=SUPER,backslash,toggle_named_scratchpad,scratch-yazi,yazi,kitty --app-id=scratch-yazi -e yazi
windowrule=isnamedscratchpad:1,width:1080,height:720,appid:scratch-yazi

