# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  { on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
  { on = "q", run = "close", desc = "Exit the process" },
  { on = "<A-q>", run = "close", desc = "Close the current tab, or quit if it's last" },

  # Operation
  { on = "s", run = "search --via=fd", desc = "Search files by name via fd" },
  { on = "S", run = "search --via=rg", desc = "Search files by content via ripgrep" },
  { on = "<C-s>", run = "escape --search", desc = "Cancel the ongoing search" },

  # Goto
  { on = ["g", "h"], run = "cd ~" },
  { on = ["g", "c"], run = "cd ~/.config" },
  { on = ["g", "C"], run = "cd ~/Repos/dotfiles" },
  { on = ["g", "d"], run = "cd ~/Downloads" },
  { on = ["g", "v"], run = "cd ~/Videos" },
  { on = ["g", "p"], run = "cd ~/Pictures" },
  { on = ["g", "G"], run = "cd ~/Grimoire" },
  { on = ["g", "k"], run = "cd ~/Kuliah" },
  { on = ["g", "R"], run = "cd ~/Repos" },
  { on = ["g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to git root folder" },
  { on = "y", run = [
    'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
    "yank"
  ] },

  # --- ./plugins/confirm-quit/main.lua
  { on = "q", run = "plugin confirm-quit", desc = "Confirm before quitting if multiple tabs are open" },

  # --- https://github.com/boydaihungst/mediainfo
  { on = "<F3>", run = "plugin mediainfo -- toggle-metadata", desc = "Toggle media preview metadata" },
  { on = "<F4>", run = "plugin mediainfo -- toggle-preview", desc = "Toggle media preview image" },

  # Hide and show metadata, image
  { on = "<F6>", run = "plugin mediainfo -- hide-metadata", desc = "Hide media preview metadata" },
  { on = "<F7>", run = "plugin mediainfo -- hide-preview", desc = "Hide media preview image" },

  { on = "<F8>", run = "plugin mediainfo -- show-metadata", desc = "Show media preview metadata" },
  { on = "<F9>", run = "plugin mediainfo -- show-preview", desc = "Show media preview image" },

  # Reset to default settings in yazi.toml file
  { on = "<F5>", run = "plugin mediainfo -- reset", desc = "Reset media preview to default settings" },

  # Use multiple actions
  { on = "<F10>", run = "plugin mediainfo -- --toggle-preview --toggle-metadata", desc = "Toggle both media preview image and metadata" },
  { on = "<F11>", run = "plugin mediainfo -- --show-preview --hide-metadata", desc = "Show media preview image and hide metadata" },
  # You can also use all of them together (7 actions above). Priority is reset > toggle > hide > show
  { on = "<F12>", run = "plugin mediainfo -- --show-preview --hide-metadata --reset --show-metadata --hide-preview", desc = "Show media preview image and hide metadata" },

  # --- https://github.com/ndtoan96/ouch.yazi
  { on = ["C"], run = "plugin ouch", desc = "Compress with ouch" },

  # --- https://github.com/Lil-Dank/lazygit.yazi
  { on = ["g", "i"], run = "plugin lazygit", desc = "run lazygit" },

  # --- https://github.com/uhs-robert/recycle-bin.yazi
  { on = ["R", "b"], run = "plugin recycle-bin", desc = "Open Recycle Bin menu" },
  { on = ["R", "o"], run = "plugin recycle-bin -- open", desc = "Open Trash" },
  { on = ["R", "e"], run = "plugin recycle-bin -- empty", desc = "Empty Trash" },
  { on = ["R", "D"], run = "plugin recycle-bin -- emptyDays", desc = "Empty by days deleted" },
  { on = ["R", "d"], run = "plugin recycle-bin -- delete", desc = "Delete from Trash" },
  { on = ["R", "r"], run = "plugin recycle-bin -- restore", desc = "Restore from Trash" },

  # --- https://github.com/boydaihungst/restore.yazi
  { on = ["u"], run = "plugin restore", desc = "Restore last deleted files/folders" },
  { on = ["U"], run = "plugin restore -- --interactive", desc = "Restore deleted files/folders (Interactive)" },
]

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"
